name: Reusable Python Quality Checks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: 'string'
      action:
        required: true
        type: 'string'

jobs:
  run_action:
    if: ${{inputs.python-version}} == '3.9' || ${{inputs.python-version}} == '3.10'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{inputs.python-version}}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Lint
        if: ${{inputs.action}} == 'lint'
        run: flake8 src tests
      
      - name: Run Tests
        if: ${{inputs.action}} == 'test'
        run: |
          PYTHONPATH=src pytest
  
  docker-build:
    needs: run_action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: python-app:${{ github.sha }}
      
      - name: List Docker images
        run: docker images